"""bigbang_bot

Revision ID: 21beec2d9cd7
Revises: 
Create Date: 2024-01-11 22:25:42.800537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from config.jsonencodeddict import JsonEncodedDict

# revision identifiers, used by Alembic.
revision: str = '21beec2d9cd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enviar_everyone', sa.Boolean(), nullable=False),
    sa.Column('enviar_dm', sa.Boolean(), nullable=False),
    sa.Column('ids_ignorados', sa.String(), nullable=False),
    # sa.Column('ids_ignorados', config.jsonencodeddict.JsonEncodedDict(), nullable=False),
    sa.Column('canal_checkpoint_id', sa.String(), nullable=False),
    sa.Column('canal_planilha_id', sa.String(), nullable=False),
    sa.Column('alerta_checkpoint_horario', sa.DateTime(), nullable=False),
    sa.Column('verificar_checkpoint_horario', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot')
    # ### end Alembic commands ###
