"""bigbang

Revision ID: 517d2ef83011
Revises: 
Create Date: 2024-01-15 17:46:04.236112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517d2ef83011'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('enviar_everyone', sa.Boolean(), nullable=True),
    sa.Column('enviar_dm', sa.Boolean(), nullable=True),
    sa.Column('ids_ignorados', sa.String(), nullable=True),
    sa.Column('canal_checkpoint_id', sa.Integer(), nullable=True),
    sa.Column('canal_planilha_id', sa.Integer(), nullable=True),
    sa.Column('alerta_checkpoint_horario', sa.DateTime(), nullable=True),
    sa.Column('verificar_checkpoint_horario', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot')
    # ### end Alembic commands ###
